/*
select REST_INFO.REST_ID,REST_INFO.REST_NAME,REST_INFO.FOOD_TYPE,REST_INFO.FAVORITES,REST_INFO.ADDRESS, round(avg(REST_REVIEW.REVIEW_SCORE),2) as SCORE
from REST_INFO, REST_REVIEW
where REST_INFO.REST_ID = REST_REVIEW.REST_ID
    and REST_INFO.ADDRESS like "서울%"
order by round(avg(REST_REVIEW.REVIEW_SCORE),2) desc, REST_INFO.FAVORITES desc
;
*/

select REST_INFO.REST_ID,REST_INFO.REST_NAME,REST_INFO.FOOD_TYPE,REST_INFO.FAVORITES,REST_INFO.ADDRESS,round(avg(REST_REVIEW.REVIEW_SCORE),2) as SCORE
from REST_INFO, REST_REVIEW
where REST_INFO.REST_ID = REST_REVIEW.REST_ID
    and REST_INFO.ADDRESS like "서울%"
group by REST_INFO.REST_ID
order by round(avg(REST_REVIEW.REVIEW_SCORE),2) desc, REST_INFO.FAVORITES desc
;

