SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') #해당 비트가 있는 경우
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') # 해당 비트가 ㅇ벗는 경우
ORDER BY ID;
