-- 총주문량이 작은 순서대로 조회
SELECT ICECREAM_INFO.INGREDIENT_TYPE, sum(FIRST_HALF.TOTAL_ORDER) as TOTAL_ORDER
from FIRST_HALF
inner join ICECREAM_INFO
    on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by INGREDIENT_TYPE
order by sum(FIRST_HALF.TOTAL_ORDER)
